--
title: "Combine song and motif data"
author: "Michael Gilchrist"
date: "date: 2025-03-04"
output: pdf_document
---

# Goal

- Combine earlier dataset on songs with newer dataset that includes both song and motif data.
- The original song data has lots of additional variables associated with it, such as chamber temperature, etc.


## Match `so` to `motif_data_full`

- match by male and date
```{r}
library(tidyverse)

```

```{r}
load(file.path("output", "data.processing_2025-03-03_process.motif.data.Rda"), verbose = TRUE)
load(file.path("output", "data.processing_2025-03-04_process.original.song.data.Rda"), verbose = TRUE)

## Avoid ambiguity and poor terminology in previous work
## at the song level
# song_data_full <- motif_data_full |>
#  rename_with( ~str_replace( .x, "motif", "song"))  |>
#  rename_with( ~str_replace(.x, "^count", "song_count"))
trial_info <- motif_data_full[ , c("male", "date", "trial_round", "temp_target", "temp_mean", "humidity_mean", "vpd", "chamber", "counter", "test_order", "mass")]

## Add trial information to motif data
song_motif_chamber_data <- left_join(song_data, trial_info, by = c("male", "date"))

## Add motif stats to song_data

song_motif_stats <- left_join(motif_data_full, song_summary, by = c("male", "date")) |>
    relocate(motif_count.y, .after="motif_count.x") %>%
    relocate(date, .before="motif_count.x") %>%
#    mutate(song_count.y = if_else(is.na(song_count.y), 0, song_count.y)) %>%
    identity()

song_motif_stats %>% filter(is.na(motif_count.y))
song_motif_stats %>% filter(is.na(motif_count.x))


right_join_song_motif_stats <- right_join(motif_data_full, song_summary, by = c("male", "date")) |>
    relocate(motif_count.y, .after="motif_count.x") %>%
    relocate(date, .before="motif_count.x") %>%
#    mutate(motif_count.y = if_else(is.na(motif_count.y), 0, motif_count.y)) %>%
    identity()

right_join_song_motif_stats %>% filter(is.na(motif_count.y))
right_join_song_motif_stats %>% filter(is.na(motif_count.x))

write_csv(x=song_motif_stats, file = file.path("output", "song_motif_stats.csv"))
write_csv(x=song_motif_chamber_data, file = file.path("output", "song_motif_chamber_data.csv"))
```

## Plot Data
```{r}

data <- song_motif_stats



not_equal_count <- which(data$motif_count.x!=data$motif_count.y)
not_equal_motif <- which(data$motif_count.x!=data$motif_motif_sum)
too_few_motifs <- which(data$motif_motif_sum < data$motif_count.y)

data[not_equal_count, c("motif_count.x", "motif_count.y", "motif_sum")] |> print(n=150)
data[too_few_motifs, c("motif_count.x", "motif_count.y", "motif_sum")] |> print(n=150)

which(data$motif_count.x==0 & data$motif_count.y>0)

data %>% filter(motif_count.x==0 & motif_count.y>0)

gg <- ggplot(data = data, aes(motif_count.x, motif_count.y))

gg + geom_point() +
    geom_smooth(method='lm', formula= y~x)


gg <- ggplot(data = data, aes(song_motif_sum, motif_count.x))

gg + geom_point() +
    geom_smooth(method='lm', formula= y~x)

gg <- ggplot(data = data, aes(motif_count, motif_count.x))

gg + geom_point() +
    geom_smooth(method='lm', formula= y~x) +
    geom_abline()

data %>% filter(song_count > 0 & motif_count.x == 0)
```
