---
title: "Merge fixed motif data into previous motif_count data"
author: "Michael Gilchrist"
date: "date: 2025-03-20"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  warning = TRUE, # show warnings
  message = TRUE, # show messages
  error = TRUE, # do not interrupt generation in case of errors,
  echo = TRUE#,  # show R code
  ##results="asis" # Hopefully print summary() in for loops
  )


```
# Goal

- Merge updated motif data into pre-existing dataset.
- Updated 2025-03-12 to use merged file of corrections from 02-16 and 03-11
- Updated 2025-03-20 to use (partially) corrected main song file: `song.by.motif.data_2025-03-20_corrected.csv`

# Set up

## Load libraries

```{r}


## load libraries
library(stats)
#require(MASS) # provides negative binomial fitting:  glm.nb
library(tidyverse)

```
## Local Functions

```{r}

```


## Load Data

```{r}

git_root <- system("git rev-parse --show-toplevel", intern=TRUE)
output_dir <- "output"
## This was the original data which as flaws and *some* corrections per tara's email on 03-18-2025
data_flawed <- read.csv(file.path(git_root, "data", "song", "song.by.motif.data_2025-03-20_corrected.csv"))
# data_fixes <- read.csv(file.path(git_root, "data", "song", "Tara.Empson_2025-02-16_fixed.motif.data.csv"))
## Update file used
## Note on 2025-04-28,  I converted T243_April_15_2022 dates to T243_April_16_2022 dates per Tara's email on 03-18
## This fix needed to be implemented 
data_fixes <- read.csv(file.path(git_root, "data", "song", "Tara.Empson_2025-02-16.and.03-11_combined.csv"))

clipped_file_name_fix <- data_fixes$Clipped.File.Name

data_flawed |>
    filter( !(Clipped.File.Name %in% clipped_file_name_fix)) -> data_tmp

data <- bind_rows(data_fixes, data_tmp) %>%
    arrange(Male, Date, Clipped.File.Name) %>%
    identity()

write_csv(data, file = file.path("output", "song.data_2025-03-20_corrected.and.merged.csv"),
          quote="needed"
)

```
